spring:
  application:
    name: ms-fas-pagamento

  flyway:
    enabled: true
    user: ms_fas_pagamento_user
    password: ms_fas_pagamento_password
    url: jdbc:postgresql://localhost:5433/ms_fas_pagamento_db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ms_fas_pagamento_db
    username: ms_fas_pagamento_user
    password: ms_fas_pagamento_password

  rabbitmq:
    host: localhost
    port: 5672
    username: ms-fas
    password: ms-fas


msfaspagamento:
  messagebroker:
    rabbitmq:
      pedido-criado:
        exchange: pedidocriado.v1.fanoutexchange
        queue: pedidocriado.v1.pagamento.queue
        duravel: true

server:
  port: 8081