CREATE TABLE PEDIDO
(
    ID               SERIAL PRIMARY KEY       NOT NULL,
    CLIENTE_UUID     UUID                     NOT NULL,
    VALOR_TOTAL      NUMERIC(10, 2)           NOT NULL,
    ENDERECO_ENTREGA JSONB                    NOT NULL,
    STATUS           VARCHAR(20)              NOT NULL,
    DATA_CRIACAO     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    DATA_ATUALIZACAO TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE PEDIDO_ITEM
(
    ID             SERIAL PRIMARY KEY NOT NULL,
    PEDIDO_ID      INTEGER,
    LIVRO_UUID     UUID               NOT NULL,
    TITULO         VARCHAR(255)       NOT NULL,
    QUANTIDADE     INT                NOT NULL,
    PRECO_UNITARIO NUMERIC(10, 2)     NOT NULL,
    SUBTOTAL       NUMERIC(10, 2)     NOT NULL,
    CONSTRAINT FK_PEDIDO
        FOREIGN KEY (PEDIDO_ID)
            REFERENCES PEDIDO (ID)
            ON DELETE CASCADE
);

CREATE INDEX IDX_PEDIDO_STATUS ON PEDIDO (STATUS);
CREATE INDEX IDX_PEDIDO_CLIENTE_ID ON PEDIDO (CLIENTE_UUID);
CREATE INDEX IDX_PEDIDO_ITEM_PEDIDO_ID ON PEDIDO_ITEM (PEDIDO_ID);
CREATE INDEX IDX_PEDIDO_ITEM_LIVRO_ID ON PEDIDO_ITEM (LIVRO_UUID);
