CREATE TABLE PAGAMENTO
(
    ID               SERIAL PRIMARY KEY       NOT NULL,
    PEDIDO_ID        UUID                     NOT NULL,
    CLIENTE_ID       UUID                     NOT NULL,
    TRANSACAO_ID     UUID                     NOT NULL,
    VALOR            NUMERIC(10, 2)           NOT NULL,
    MOEDA            VARCHAR(3)               NOT NULL DEFAULT 'BRL',
    STATUS           VARCHAR(15)              NOT NULL DEFAULT 'PENDENTE',
    TIPO             VARCHAR(15)              NOT NULL,
    DATA_CRIACAO     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    DATA_ATUALIZACAO TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IDX_PAGAMENTO_STATUS ON PAGAMENTO (STATUS);
CREATE INDEX IDX_PAGAMENTO_PEDIDO_ID ON PAGAMENTO (PEDIDO_ID);
CREATE INDEX IDX_PAGAMENTO_CLIENTE_ID ON PAGAMENTO (CLIENTE_ID);
